name: build

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          overwrite-settings: false
      - name: Publish package
        run: mvn -B -e -Dmaven.wagon.http.pool=false deploy
        env:
          DEPLOY_TOKEN: '${{ secrets.DEPLOY_TOKEN }}'
